Make Codespell happy
Fix the following errors:
```
Error: ./pkg/datasource/service.go:247: valie ==> value, valid
Error: ./pkg/manager/service.go:460: sourece ==> source
Error: ./pkg/manager/service.go:475: sourece ==> source
```

Signed-off-by: Volker Theile <vtheile@suse.com>
(cherry picked from commit c140ba91821569e12f0f71f19a21b08d79adb27c)